languageCode = "en-us"
title = "ilumino Pattern Library"
baseURL = "https://ilumino-project.github.io/cupper/"
canonifyURLs = true
theme = "ilumino"
publishDir = "docs"

[params]
  description = "Documentation for the **ilumino Pattern Library** documentation builder, built with **Cupper**."
  codePenUser = "desjardy"

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  tag = "tags"
  guideline = "guidelines"
  principle = "principles"
