languageCode = "en-us"
title = "Cupper"
baseURL = "https://ilumino-project.github.io/cupper/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Documentation for the **Cupper** documentation builder, built with **Cupper** itself."
  codePenUser = "Heydon"
